FROM markhobson/maven-chrome:jdk-17

# Set working directory
WORKDIR /app

# Copy pom.xml and source code
COPY selenium-tests/pom.xml .
COPY selenium-tests/src ./src

# Create a place for results
RUN mkdir -p target/surefire-reports

# Default command to run tests
# We use 'mvn test'
# Environment variables like APP_URL should be passed at runtime
CMD ["mvn", "test"]
